FROM centos:7 as builder

RUN yum install -y java-1.8.0-openjdk-devel curl tar && \
    mkdir -p /usr/local/tomcat && \
    yum clean all

COPY apache-tomcat-9.0.89.tar.gz /usr/local/tomcat/
COPY mysql-connector-java-8.0.29-1.el7.noarch.rpm /usr/local/tomcat/

RUN tar -xzf /usr/local/tomcat/apache-tomcat-9.0.89.tar.gz -C /usr/local/tomcat --strip-components=1 && \
    yum localinstall -y /usr/local/tomcat/mysql-connector-java-8.0.29-1.el7.noarch.rpm && \
    cp /usr/share/java/mysql-connector-java-8.0.29.jar /usr/local/tomcat/lib/ && \
    rm /usr/local/tomcat/apache-tomcat-9.0.89.tar.gz && \
    rm -rf /usr/local/tomcat/webapps/examples \
           /usr/local/tomcat/webapps/docs \
           /usr/local/tomcat/webapps/manager \
           /usr/local/tomcat/webapps/host-manager && \
    chmod +x /usr/local/tomcat/bin/*.sh

COPY index.html /usr/local/tomcat/webapps/ROOT/
COPY ./post /usr/local/tomcat/webapps/ROOT/

# Final stage
FROM centos:7

RUN yum install -y java-1.8.0-openjdk && \
    yum clean all && \
    rm -rf /var/cache/yum

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $JAVA_HOME/bin:$CATALINA_HOME/bin:$PATH

COPY --from=builder /usr/local/tomcat /usr/local/tomcat

EXPOSE 8080

CMD ["catalina.sh", "run"]
